development:
  adapter: postgresql
  database: benkoloski_development
  pool: 5
  timeout: 5000

# test:
#   adapter: postgresql
#   database: db/test.sqlite3
#   pool: 5
#   timeout: 5000

production:
  adapter: postgresql
  host: shared-basic.cihmxmcs4uik.us-west-2.rds.amazonaws.com
  username: benkoloski
  password: 'benkoloski001'
  database: benkoloski_production
  pool: 5
  timeout: 5000

